#!/bin/bash
# ws-signer
# chkconfig: 345 20 80
# description: ws-signer daemon
# processname: ws-signer


# The keystore password.
if [ -z "$WS_SIGNER_PASSWORD" ]; then
  WS_SIGNER_PASSWORD=35120499
fi
export WS_SIGNER_PASSWORD

DAEMON_PATH="/home/ubuntu/ws-signer/ws-signer-1.1.4"
DAEMON="java -jar ws-signer-1.1.4.jar"
DAEMONOPTS=

NAME=ws-signer
DESC="WS-Signer Daemon"
LOGFILE=$DAEMON_PATH/console.log
PIDFILE=/var/run/$NAME.pid
SCRIPTNAME=/etc/init.d/$NAME


case "$1" in
start)
	printf "%-50s" "Starting $NAME..."
	cd $DAEMON_PATH
	PID=`$DAEMON $DAEMONOPTS > $LOGFILE 2>&1 & echo $!`
	#echo "Saving PID" $PID " to " $PIDFILE
        if [ -z $PID ]; then
            printf "%s\n" "Fail"
        else
            echo $PID > $PIDFILE
            printf "%s\n" "Ok"
        fi
;;
status)
        printf "%-50s" "Checking $NAME..."
        if [ -f $PIDFILE ]; then
            PID=`cat $PIDFILE`
            if [ -z "`ps axf | grep ${PID} | grep -v grep`" ]; then
                printf "%s\n" "Process dead but pidfile exists"
            else
                echo "Running"
            fi
        else
            printf "%s\n" "Service not running"
        fi
;;
stop)
        printf "%-50s" "Stopping $NAME"
            PID=`cat $PIDFILE`
            cd $DAEMON_PATH
        if [ -f $PIDFILE ]; then
            kill -HUP $PID
            printf "%s\n" "Ok"
            rm -f $PIDFILE
        else
            printf "%s\n" "pidfile not found"
        fi
;;
restart)
    $0 stop
    $0 start
;;
*)
    echo "Usage: $0 {status|start|stop|restart}"
    exit 1
esac
